In [7]:
from numpy import *
a=array([1,2,3]) #1D
print(a, '\n')
b=array([[1,2,3], [4,5,6]]) #2D
print(b, '\n')
c=array([[[1,2,3],[4,5,6]], [[7,8,9], [1,5,9]]]) #3D
print(c, '\n')

print(a.ndim) # ndim represents number of dimensions
print(b.ndim)
print(c.ndim)

print(a.shape)
print(b.shape) # shape gives shape of array for 1D num of elements and for 2D (number of rows,number of coloums)
b.shape=(3, 2) # also chages the shape of array
print(b)
print('\n')
print(a.size)
print(b.size) # size gives total number of elements
print(c.size)
print('\n')
print(a.itemsize)
print(b.itemsize) #itemsize gives the memory size of the array element in bytes
print(c.itemsize)
print('\n')
print(b.dtype) #dtype gives datatype of elements
print('\n')
print(c.nbytes) # nbytes gives the total number of bytes occupied by an array
print('\n')
b=b.reshape(3,2) # reshape() method changes the shape of an array
print(b, '\n')
print(b.flatten())# flatten() method converts 2D into 1D


[1 2 3] 

[[1 2 3]
 [4 5 6]] 

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 5 9]]] 

1
2
3
(3,)
(2, 3)
[[1 2]
 [3 4]
 [5 6]]


3
6
12


8
8
8


int64


96


[[1 2]
 [3 4]
 [5 6]] 

[1 2 3 4 5 6]
[1 2 3]
