In [16]:
from array import *
a = array('i', [])
print('how many element', )
n=int(input())
for  i in range(n):
        a.append(int(input()))
    # array library includes array methods
print(a)

how many element
5
5
4
6
3
2
array('i', [5, 4, 6, 3, 2])


In [6]:
from numpy import *
a = arange(6)
print(a)
b=a.reshape(2,3)
for i in range(len(b)):
    print(b[i]) # nly rows
for i in range(len(b)):
    for  j in range(len(b[i])):
        print(b[i][j])

[0 1 2 3 4 5]
[0 1 2]
[3 4 5]
0
1
2
3
4
5
