In [14]:
import numpy as np
d =np.random.randn(2, 3) # tp create random data
print(d)
print(d*10)
print(d+d)
print(d.dtype)
print(type(d))
print(d.shape)
d.shape=(3,2)
print(d)

[[ 0.75459795  0.78910873  1.01577244]
 [ 0.91233354 -0.09888536  0.5725745 ]]
[[ 7.54597952  7.89108731 10.1577244 ]
 [ 9.12333545 -0.98885359  5.72574499]]
[[ 1.5091959   1.57821746  2.03154488]
 [ 1.82466709 -0.19777072  1.145149  ]]
float64
<class 'numpy.ndarray'>
(2, 3)
[[ 0.75459795  0.78910873]
 [ 1.01577244  0.91233354]
 [-0.09888536  0.5725745 ]]


In [24]:
#creating an array
import numpy as np
d=[2,3,4,5]
d1=[[2,3,4,5,6],[4,5,6,7,8]]
a=np.array(d)
print(a)
a1=np.array(d1)
print(a1)
a4=np.array([2,4,5,6], dtype=np.float)
print(a4 , a4.dtype)
print(a1.ndim) # to check dimensions
a2=np.zeros(10)
print(a2)
a2=np.zeros((2,2))
print(a2)
a3=np.zeros((2,2), dtype=float) 
print(a3)
a2=np.ones(10)
print(a2)
a2=np.ones((2,2))
print(a2)
a3=np.ones((2,2), dtype=float) 
print(a3 , a3.dtype)

[2 3 4 5]
[[2 3 4 5 6]
 [4 5 6 7 8]]
[2. 4. 5. 6.] float64
2
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]] float64


In [18]:
import numpy as np
from array import *
# asarray() == Convert input to ndarray, but do not copy if the input is already an ndarray
# Syntax : numpy.asarray(arr, dtype=None, order=None) 

a1=np.array([2,3,4])
print(a1)
a2=np.copy(a1)
a3=a2
print('jj',a2)
print(a1,   a2,  a3)
a1=np.asarray(a1)
print(a1)
a1=[1,3,4,5]
a1=np.asarray(a1)
print(a1)
a = np.array([1, 2, 3])
print(np.array(a) is a)
print(np.asarray(a) is a)

[2 3 4]
jj [2 3 4]
[2 3 4] [2 3 4] [2 3 4]
[2 3 4]
[1 3 4 5]
False
True


In [2]:
import numpy as np
# numpy.empty(shape, dtype = float, order = ‘C’)
# Create new arrays by allocating new memory, but do not populate with any values like ones and zeros

a=np.empty([2,2])
print(a)
b=np.ones_like(a, dtype=int) # zeros_like same for all empty and full
# ones_like takes another array and produces a ones array of the same shape and dtype.
print(b)

# numpy.full(shape, fill_value, dtype = None, order = ‘C’)

b=np.full([2,2],2)
print(b)
d=np.empty_like(b)
print(d)
d=np.eye(2,2, dtype=int) #eye(r,c,dtype,order)
print(d)
print(np.full_like(d, 4))

[[5.e-324 5.e-324]
 [5.e-324 5.e-324]]
[[1 1]
 [1 1]]
[[2 2]
 [2 2]]
[[1 1]
 [1 1]]
[[1 0]
 [0 1]]
[[4 4]
 [4 4]]


In [13]:
import numpy as np

a=np.array([[1,2,3,],[4,5,6]])
print(a)
b=a # aliasing or viewing
print(b)
a[0][1]=10
print(a)
print(b) # change will happen in both 
b=a.copy()
print(b)
a[1][0]=9
print(a) # change will happen only in a
print(b)

c=np.array([[1,2,3],[9,8,7]])
print( 'c is ', c)
print(c-a)
print(a+b)
print(a*b)
print(a/2)
print(c>a)
print(a==c)
d=a[[0][0]:[1][0]]
print(d)
d=np.arange(10)
print(d)
print(d[2:4].copy())
r=np.arange(4).reshape(2,2)
print(r)
print(r.dtype)
print(r.astype(np.float)) # astype() to convert into another type

a=np.arange(9).reshape(3,3)
print(a)
print(a[:2, :2])
print(a[1:, :2])

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 1 10  3]
 [ 4  5  6]]
[[ 1 10  3]
 [ 4  5  6]]
[[ 1 10  3]
 [ 4  5  6]]
[[ 1 10  3]
 [ 9  5  6]]
[[ 1 10  3]
 [ 4  5  6]]
c is  [[1 2 3]
 [9 8 7]]
[[ 0 -8  0]
 [ 0  3  1]]
[[ 2 20  6]
 [13 10 12]]
[[  1 100   9]
 [ 36  25  36]]
[[0.5 5.  1.5]
 [4.5 2.5 3. ]]
[[False False False]
 [False  True  True]]
[[ True False  True]
 [ True False False]]
[[ 1 10  3]]
[0 1 2 3 4 5 6 7 8 9]
[2 3]
[[0 1]
 [2 3]]
int64
[[0. 1.]
 [2. 3.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [3 4]]
[[3 4]
 [6 7]]


In [2]:
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)
print(arr3d.shape)
s=np.shape(arr3d)
print(s)
print(arr3d[0])
a=np.transpose(arr3d)
print(a)
arr3d[:]=33 
print(arr3d)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
(2, 2, 3)
[[1 2 3]
 [4 5 6]]
[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]
[[[33 33 33]
  [33 33 33]]

 [[33 33 33]
  [33 33 33]]]


In [13]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(names)
print(names=='Bob')
print('\n')
data=np.random.randn(7,4)
print(data)
print('\n')
print(data[names=='Bob']) # The boolean array must be of the same length as the axis(rows) it’s indexing
print('\n')
print(data[names=='Bob' , :2]) # rows of data array will be printed when names==bob will be true
print('\n')
print(data[names=='Bob' , 2:])
data[0:2]=10
print('\n')
print(data)
a=np.ones_like(data, dtype=np.int)
print(a, '\n')
e=np.empty_like(data)
print(e)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[ True False False  True False False False]


[[ 1.22073704  0.28410419 -0.33045799 -0.03644554]
 [-0.93376066  0.86209478  0.91621374 -0.56849087]
 [ 0.85088492  0.10573183 -0.97823546  0.51779167]
 [ 1.48252981 -2.15501081 -0.15842964 -0.88388578]
 [ 1.00725448  0.77129283  0.04900199 -0.45231787]
 [ 0.22933881  1.33709226 -0.31378038  1.46735843]
 [ 2.02022403 -0.48336369  0.9434628   1.12005935]]


[[ 1.22073704  0.28410419 -0.33045799 -0.03644554]
 [ 1.48252981 -2.15501081 -0.15842964 -0.88388578]]


[[ 1.22073704  0.28410419]
 [ 1.48252981 -2.15501081]]


[[-0.33045799 -0.03644554]
 [-0.15842964 -0.88388578]]


[[10.         10.         10.         10.        ]
 [10.         10.         10.         10.        ]
 [ 0.85088492  0.10573183 -0.97823546  0.51779167]
 [ 1.48252981 -2.15501081 -0.15842964 -0.88388578]
 [ 1.00725448  0.77129283  0.04900199 -0.45231787]
 [ 0.22933881  1.33709226 -0.31378038  1.46735843]
 [ 2.02022403 -0.483363

In [3]:
# fancy indexing
arr=np.empty((8,4))
print( arr)
print('\n', len(arr))
for i in range(8):
    arr[i]=i+1 
print(arr)    
#To select out a subset of the rows in a particular order, you can simply pass a list or
#ndarray of integers specifying the desired order:

arr1=arr[[0,7,4,5]] # return 0th , 7th,4th,5th row
print(arr1)
print('\n', arr1[[0,1]])
print(arr[[-1,-2,-4]],'\n')
a=np.arange(32).reshape(8,4)
print(a ,'\n')
print(a[[1,2,3,4],[0,2,3,1]])

[[6.89900508e-310 6.89900508e-310 4.64606190e-310 1.58595072e-321]
 [4.64606326e-310 6.89902985e-310 6.89900508e-310 6.89900508e-310]
 [6.89900508e-310 6.89900508e-310 6.89900508e-310 6.89900508e-310]
 [6.89900508e-310 6.89900508e-310 6.89900508e-310 6.89900508e-310]
 [6.89900508e-310 6.89900508e-310 6.89900508e-310 6.89900508e-310]
 [6.89900508e-310 6.89900508e-310 6.89900508e-310 6.89900508e-310]
 [6.89900508e-310 6.89900508e-310 6.89900508e-310 6.89900508e-310]
 [6.89900508e-310 6.89900508e-310 6.89900508e-310 6.89900508e-310]]

 8
[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]
 [8. 8. 8. 8.]]
[[1. 1. 1. 1.]
 [8. 8. 8. 8.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]]

 [[1. 1. 1. 1.]
 [8. 8. 8. 8.]]
[[8. 8. 8. 8.]
 [7. 7. 7. 7.]
 [5. 5. 5. 5.]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] 

[ 4 10 15 17]


In [8]:
# Transposing Arrays and Swapping Axes
import numpy as np
arr = np.arange(15).reshape((3, 5))
print(arr, '\n')
print(arr.T) #transpose
print('\n',np.transpose(arr))

#dot matrix computation
a=np.arange(4).reshape(2,2)
print(a, '\n')
b=np.arange(4).reshape(2,2)
print(b)
print('\n', np.dot(a,b)) # multiplication




[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]

 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[0 1]
 [2 3]] 

[[0 1]
 [2 3]]

 [[ 2  3]
 [ 6 11]]


In [16]:
#Universal Functions: Fast Element-wise Array Functions
import numpy as np
a=np.arange(10)
print(a,'\n')
print(np.sqrt(a), '\n')# compute the square root of each element.Equivalent to arr ** 0.5
print(np.square(a), '\n') # compute the square root of each element.Equivalent to arr ** 2
print(np.exp(a), '\n') # Compute the exponent e x of each element
#add or maximum , take 2 arrays
#(thus, binary ufuncs) and return a single array as the result:

b=np.arange(10,20)
c=np.array([10,2,38,4,5,60,7,8,90,9])
print(b , '\n')
print(np.maximum(c,b),'\n') # element-wise maximum ANd shape of both array should be same 
print(np.add(a,b)) # Add corresponding elements in arrays and subtract() do same
m=list(map(lambda x,y:x+y , a,b))
print(m,'\n')

[0 1 2 3 4 5 6 7 8 9] 

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ] 

[ 0  1  4  9 16 25 36 49 64 81] 

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03] 

[10 11 12 13 14 15 16 17 18 19] 

[10 11 38 13 14 60 16 17 90 19] 

[10 12 14 16 18 20 22 24 26 28]
[10, 12, 14, 16, 18, 20, 22, 24, 26, 28] 



In [ ]:

Unary ufuncs   Function Description
abs, fabs  Compute the absolute value element-wise for integer, floating point, or complex values.
           Use fabs as a faster alternative for non-complex-valued data

sqrt  Compute the square root of each element. Equivalent to arr ** 0.5

square Compute the square of each element. Equivalent to arr ** 2

exp Compute the exponent e x of each element
log, log10, log2, log1p   Natural logarithm (base e), log base 10, log base 2, and log(1 + x), respectively

sign  Compute the sign of each element: 1 (positive), 0 (zero), or -1 (negative)
    
ceil  Compute the ceiling of each element, i.e. the smallest integer greater than or equal to
      each element
    
floor  Compute the floor of each element, i.e. the largest integer less than or equal to each
       element

rint   Round elements to the nearest integer, preserving the dtype

modf   Return fractional and integral parts of array as separate array

isnan  Return boolean array indicating whether each value is NaN (Not a Number)

isfinite, isinf  Return boolean array indicating whether each element is finite (non- inf , non- NaN ) or
                  infinite, respectively
cos, cosh, sin, sinh,
tan, tanh                   Regular and hyperbolic trigonometric functions
arccos, arccosh, arcsin,
arcsinh, arctan, arctanh    Inverse trigonometric functions
logical_not                 Compute truth value of not x element-wise. Equivalent to -arr .





In [ ]:
Binary universal functions

Function    Description
add          Add corresponding elements in arrays 

subtract      Subtract elements in second array from first array

multiply   Multiply array elements

divide, floor_divide   Divide or floor divide (truncating the remainder)

power     Raise elements in first array to powers indicated in second array

maximum, fmax   Element-wise maximum. fmax ignores NaN 

minimum, fmin   Element-wise minimum. fmin ignores NaN

mod        Element-wise modulus (remainder of division)

copysign   Copy sign of values in second argument to values in first argument

In [ ]:
greater, greater_equal,
less, less_equal, equal,
not_equal                 Perform element-wise comparison, yielding boolean array. Equivalent to infix operators
                          >, >=, <, <=, ==, !=,
logical_and,
logical_or, logical_xor   Compute element-wise truth value of logical operation. Equivalent to infix operators 
                          &, |, ^

In [26]:
arr = np.random.randn(7)*5
print(arr)
print(np.modf(arr))
a=np.array([8, 6])
print(a)
print(np.modf(a))
a=np.arange(4)
b=np.ones_like(a)
print( a   , b)
print(np.power(b,a))
print(np.mod(b,a))

[-6.8997106   9.13667944 -2.1981165   0.58222734  0.66390952 -2.72077485
  3.68667847]
(array([-0.8997106 ,  0.13667944, -0.1981165 ,  0.58222734,  0.66390952,
       -0.72077485,  0.68667847]), array([-6.,  9., -2.,  0.,  0., -2.,  3.]))
[8 6]
(array([0., 0.]), array([8., 6.]))
[0 1 2 3] [1 1 1 1]
[1 1 1 1]
[0 0 1 1]


/home/shubham/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in remainder
  # This is added back by InteractiveShellApp.init_path()
